### ISSUE TITLE
Customer class Missing

### ISSUE THREAD

**Issue by kali786516** [simplesteph/kafka-avro-course#4]
https://github.com/simplesteph/kafka-avro-course/blob/05050c3bfedaec23e523a524cd22f38690e8f87d/kafka-avro-v1/src/main/java/com/github/simplesteph/kafka/apps/v1/KafkaAvroJavaConsumerV1Demo.java#L3

this class is missing

**Comment by simplesteph** [comment]
It's a generated class as you'll see in the course

**Comment by kali786516** [comment]
Sorry yes
